### ISSUE TITLE
Error installing package using devtools::install_github() in R4.0.2

### ISSUE THREAD

**Issue by mariaemilyd** [nicocriscuolo/StructuRly#1]
Hi Nico,

I'm getting the following error message when I try and install the package using devtools::install_github(repo = "nicocriscuolo/StructuRly", dependencies = T)

ERROR: dependency 'shinymeta' is not available for package 'StructuRly' install.packages("shinymeta")

when I try install.packages("shinymeta") it says it is not available for R4.0.2.

Do you have any idea how to solve this?

Thanks,

Maria

**Comment by mariaemilyd** [comment]
For context: I intitially tried to load the shiny app and import a STRUCTURE output .txt but it got stuck after "upload complete" and did not continue further, so I thought I would try going through R instead. 
![structuRly error](https://user-images.githubusercontent.com/40392511/100086120-d91ad400-2e44-11eb-9908-834427f1fc95.png)
[results_job_10_f.txt](https://github.com/nicocriscuolo/StructuRly/files/5589393/results_job_10_f.txt)

**Comment by CapLoris** [comment]
Hi!
Did you find a solution for that error with shinymeta dependency?

**Comment by mariaemilyd** [comment]
Hi, I just tried it again with R4.0.3 and it didn't work but then I searched for the shinymeta package, installed it using the code from here: https://github.com/rstudio/shinymeta (I had to install "remotes" package first) and then it all worked!

**Comment by CapLoris** [comment]
Great! I found out that my Rstudio version was not the latest as well. I will update and try. Thanks for the tips!

**Comment by mariaemilyd** [comment]
Your rstudio version or R version? Also tip for installing the latest R version once you have newest R studio version:  use updateR() function from installr package: https://www.r-project.org/nosvn/pandoc/installr.html

**Comment by CapLoris** [comment]
I updated both. Once installed shinymeta separetly it gave another error related to Ade4 version. By using 
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
I solved the problem. Now seems working 🥇 

Thanks for helping!

**Comment by nicocriscuolo** [comment]
Hello, and thanks for your respective comments and answers. I am really sorry for my late reply, but somehow I didn't get any notification about a new issue opened for StructuRly. I need to check how to turn them on. 

About shinymeta, I confirm that if you want to use StructuRly on you local machine, you need to install it in R through the following code: `remotes::install_github("rstudio/shinymeta")`. About ade4, with the latest version of ade4 and R everything should work fine. If you don't want to install StructuRly and all the dependencies locally, you can use the online version of the app.

Cheers!
