### ISSUE TITLE
Ajax error

### ISSUE THREAD

**Issue by ArpitGaur-Git** [nicocriscuolo/StructuRly#2]
After uploading a large data file (300 genotype x ~14500 SNP markers) when I went for 'Start Analysis' an Ajax error appeared.  I tried different browsers and the error sustained. I followed the instructions  (https://datatables.net/manual/tech-notes/7) of debugging but it didn't work at all.
<img width="960" alt="error" src="https://user-images.githubusercontent.com/79159594/115145348-b943b100-a06e-11eb-9b7b-1791630442a2.png">
.

**Comment by nicocriscuolo** [comment]
Hi @drarpitgaur24 and sorry for my super late answer but I didn't get any notification about this issue. Could you please let me know if you're still getting this error? Because I remember I updated the functionalities of StructuRly through data.table package.

Cheers,

Nico

**Comment by ArpitGaur-Git** [comment]
Dear Nicocriscuolo
Thank you for your email. You resolved the bug at the same time. Thank you.
With warm regards
Arpit Gaur
CIMMYT|BISA, India
cell: (+91)9001860730

*This e-mail may contain confidential and/or privileged information from
CIMMYT and/or its collaborators. Unless explicitly allowed in writing by an
authorized representative, any use, reproduction, storage, retransmission
or unauthorized disclosure of such information, whether in part or in
whole, is hereby forbidden. If you are not the intended recipient of this
e-mail, please notify the sender and delete it immediately.*

**Comment by nicocriscuolo** [comment]
Thank you for your prompt reply! I'm gonna close the issue then.

Cheers
