### ISSUE TITLE
Population Analysis

### ISSUE THREAD

**Issue by JunxiFeng** [nicocriscuolo/StructuRly#4]
Hello,

After I imported the raw genetic data, how do I generate the csv file needed to be used for the population analysis, I noticed that the sample data files contain the StructureAnalysis.csv that has K1, K2, K3, and K4, but I am not sure where to get such a file.

Thank you so much!

**Comment by nicocriscuolo** [comment]
Hi @JunxiFeng and thanks for using StructuRly.

The file that you are looking for must be generated outside of StructuRly, using for example a program like STRUCTURE (https://web.stanford.edu/group/pritchardlab/structure.html). From STRUCTURE you can conduct your population analysis, then extract the results, rename the different column as "K1", "K2", ecc. and then import everything in StructuRly, in the section for the population analysis and plot your results.

Hope this helps!

Nico
